### ISSUE TITLE
moogli and /or morphology

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-examples#14]
First of all, Moogli doesn't get installed by its own.
The instructions for installation mogli are to be made handy.

While running the insertSpins.py, in absence of the terminal generates 
"Warning: Moogli not found. All moogli calls will use dummy functions"

A major issue is with the morphology module.
Running the following files generate error:
"AttributeError: 'module' object has no attribute 'Morphology'"

insertSpines.py
insertSpinesWithoutRdesigneur.py
loadMorphology.py

Running the teseSigNeur.py gives:
AttributeError: 'moose.SynChan' object has no attribute 'synapse'

**Comment by dilawar** [comment]
From versionn 3.1.1, moogli is shipped with moose package. Details are here https://moose.readthedocs.io/en/master/introduction/install/index.html . You can edit any documentation page over github as you like. I'll  merge them into the source tree after review.

`moogli.Morphology` is missing. I've to check the build log and previous version if this was deprecated or fell out of package due to cmake changes.

**Comment by dilawar** [comment]
Open it again if this ticket is still valid. Closing since there was not an further response on it.
