### ISSUE TITLE
Most tests in `traub_2005` directory are failing with same error

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-examples#28]
Most scripts in `traub_2005` directory are failing, they are emit the following message:

``` 
 File "test_nachans.py", line 38, in <module>
    import testutils
  File "/home1/dilawars/SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/testutils.py", line 45, in <module>
    import channelbase
  File "/home1/dilawars/SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/channelbase.py", line 165, in <module>
    class ChannelBase(moose.HHChannel, ChannelMeta):
TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict
```

**Comment by subhacom** [comment]
This bug was introduced in commit d9cb5b7a34b311182a4a096560c2f46428c0bfca. First a fix to make traub_2005/channelbase.py work on Python 3 and then a second fix to make it syntactically back-compatible with python2 (likely without testing) broke it.
The metaclass syntax is incompatible between Python 2 and 3. Workaround exists via the six module.

**Comment by dilawar** [comment]
Thanks @subhacom . I've merged the change into master and deleted `traub_2005` branch.
